-- Generated by the database client, not guaranteed complete.
CREATE TABLE adresse(
    id_adresse character(10) NOT NULL,
    no_bat integer NOT NULL,
    ville varchar(50) NOT NULL,
    code_postal character(5) NOT NULL,
    nom_rue varchar(255) NOT NULL,
    PRIMARY KEY(id_adresse)
);


-- Generated by the database client, not guaranteed complete.
CREATE TABLE utilisateur(
    id_user character(15) NOT NULL,
    nom varchar(50) NOT NULL,
    prenom varchar(50) NOT NULL,
    num_telephone character(10) NOT NULL,
    PRIMARY KEY(id_user)
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE abonne(
    id_user character(15) NOT NULL,
    mail varchar(100) NOT NULL,
    date_naissance date NOT NULL,
    id_adresse character(15),
    password varchar(255) NOT NULL,
    balance integer NOT NULL DEFAULT 500,
    profil varchar(255),
    sexe character(5) NOT NULL,
    PRIMARY KEY(id_user),
    CONSTRAINT abonne_id_user_fkey FOREIGN key(id_user) REFERENCES utilisateur(id_user),CONSTRAINT fk_adresse FOREIGN key(id_adresse) REFERENCES adresse(id_adresse),
    CONSTRAINT abonne_balance_check1 CHECK ((balance >= 0))
);
CREATE UNIQUE INDEX uc_mail ON "abonne" USING btree ("mail");

-- Generated by the database client, not guaranteed complete.
CREATE TABLE nonabonne(
    id_user character(15) NOT NULL,
    plus varchar(50),
    PRIMARY KEY(id_user),
    CONSTRAINT nonabonne_id_user_fkey FOREIGN key(id_user) REFERENCES utilisateur(id_user)
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE plat(
    id_plat character(15) NOT NULL,
    prix integer NOT NULL,
    description varchar(100),
    image varchar(100),
    nom varchar(50),
    PRIMARY KEY(id_plat)
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE boisson(
    id_boisson character(15) NOT NULL,
    nom varchar(50),
    prix integer NOT NULL,
    image varchar(100),
    quantite_en_cl varchar(50),
    PRIMARY KEY(id_boisson)
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE menu(
    id_menu character(15) NOT NULL,
    nom varchar(50),
    prix integer NOT NULL,
    image varchar(100),
    composition varchar(100),
    description varchar(50),
    PRIMARY KEY(id_menu)
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE commande(
    id_commande character(15) NOT NULL,
    heure varchar(50) NOT NULL,
    --heure timestamp without time zone NOT NULL,
    numero integer NOT NULL,
    solde integer NOT NULL,
    statut boolean NOT NULL DEFAULT true,
    id_user character(15) NOT NULL,
    PRIMARY KEY(id_commande),
    CONSTRAINT commande_id_user_fkey FOREIGN key(id_user) REFERENCES utilisateur(id_user)
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE inclut(
    id_commande character(15) NOT NULL,
    id_menu character(15) NOT NULL,
    PRIMARY KEY(id_commande,id_menu),
    CONSTRAINT inclut_id_commande_fkey FOREIGN key(id_commande) REFERENCES commande(id_commande),CONSTRAINT inclut_id_menu_fkey FOREIGN key(id_menu) REFERENCES menu(id_menu)
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE se_compose(
    id_commande character(15) NOT NULL,
    id_plat character(15) NOT NULL,
    PRIMARY KEY(id_commande,id_plat),
    CONSTRAINT se_compose_id_commande_fkey FOREIGN key(id_commande) REFERENCES commande(id_commande),CONSTRAINT se_compose_id_plat_fkey FOREIGN key(id_plat) REFERENCES plat(id_plat)
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE contient(
    id_commande character(15) NOT NULL,
    id_boisson character(15) NOT NULL,
    PRIMARY KEY(id_commande,id_boisson),
    CONSTRAINT contient_id_commande_fkey FOREIGN key(id_commande) REFERENCES commande(id_commande),CONSTRAINT contient_id_boisson_fkey FOREIGN key(id_boisson) REFERENCES boisson(id_boisson)
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE tablerestau(
    id_table character(15) NOT NULL,
    capacite integer NOT NULL,
    nom varchar(50),
    PRIMARY KEY(id_table),
    CONSTRAINT tablerestau_capacite_check CHECK ((capacite > 0)),
    CONSTRAINT tablerestau_capacite_check1 CHECK ((capacite <= 7))
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE creneau(
    id_creneau character(15) NOT NULL,
    id_table character(15) NOT NULL,
    debut timestamp without time zone NOT NULL,
    fin timestamp without time zone NOT NULL,
    PRIMARY KEY(id_creneau),
    CONSTRAINT fktable FOREIGN key(id_table) REFERENCES tablerestau(id_table)
);

-- Generated by the database client, not guaranteed complete.
CREATE TABLE reservation(
    id_table character(15) NOT NULL,
    id_user character(15) NOT NULL,
    id_reserv character(15) NOT NULL,
    heure timestamp without time zone NOT NULL,
    validite boolean DEFAULT true,
    PRIMARY KEY(id_table,id_user,id_reserv),
    CONSTRAINT fk_id_table FOREIGN key(id_table) REFERENCES tablerestau(id_table),CONSTRAINT fk_id_user FOREIGN key(id_user) REFERENCES utilisateur(id_user)
);
CREATE UNIQUE INDEX reservation_id_reserv_key ON "reservation" USING btree ("id_reserv");


--Suppression des tables
-- Supprimer les contraintes avant de supprimer les tables
DROP TABLE IF EXISTS inclut;
DROP TABLE IF EXISTS se_compose;
DROP TABLE IF EXISTS contient;
DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS creneau;

-- Supprimer les tables principales
DROP TABLE IF EXISTS tablerestau;
DROP TABLE IF EXISTS commande;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS plat;
DROP TABLE IF EXISTS boisson;

DROP TABLE IF EXISTS nonabonne;
DROP TABLE IF EXISTS abonne;
DROP TABLE IF EXISTS utilisateur;
DROP TABLE IF EXISTS adresse;
